const CHANGE_CATEGORY = "CHANGE_CATEGORY";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";

const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export {
  CHANGE_CATEGORY,
  GET_CATEGORIES_SUCCESS,
  GET_PRODUCTS_SUCCESS,
  CREATE_PRODUCTS_SUCCESS,
  UPDATE_PRODUCTS_SUCCESS,
  ADD_TO_CART,
  REMOVE_FROM_CART,
};
